-- TABLESPACE 생성
CREATE TABLESPACE 테이블스페이스명
DATAFILE 'C:\app\oradata\orcl\TS_PRACTICE.DBF'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- USER 생성 및 권한주기
CREATE USER JOEL
IDENTIFIED BY 1
DEFAULT TABLESPACE TS_PRACTICE;

GRANT CONNECT, DBA, RESOURCE TO JOEL;

-- 테이블 시작
CREATE TABLE "JOEL"."COMTCCMMNCLCODE" 
   (	"CL_CODE" CHAR(3) NOT NULL ENABLE, 
	"CL_CODE_NM" VARCHAR2(60), 
	"CL_CODE_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNCLCODE_PK" PRIMARY KEY ("CL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."CL_CODE" IS '분류코드';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."CL_CODE_NM" IS '분류코드명';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."CL_CODE_DC" IS '분류코드설명';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCLCODE"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTCCMMNCLCODE"  IS '공통분류코드';

CREATE TABLE "JOEL"."COMTCCMMNCODE" 
   (	"CODE_ID" VARCHAR2(6) NOT NULL ENABLE, 
	"CODE_ID_NM" VARCHAR2(60), 
	"CODE_ID_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"CL_CODE" CHAR(3), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNCODE_PK" PRIMARY KEY ("CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTCCMMNCODE_FK1" FOREIGN KEY ("CL_CODE")
	  REFERENCES "JOEL"."COMTCCMMNCLCODE" ("CL_CODE") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."CODE_ID" IS '코드ID';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."CODE_ID_NM" IS '코드ID명';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."CODE_ID_DC" IS '코드ID설명';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."CL_CODE" IS '분류코드';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNCODE"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTCCMMNCODE"  IS '공통코드';

CREATE TABLE "JOEL"."COMTCCMMNDETAILCODE" 
   (	"CODE_ID" VARCHAR2(6) NOT NULL ENABLE, 
	"CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"CODE_NM" VARCHAR2(60), 
	"CODE_DC" VARCHAR2(200), 
	"USE_AT" CHAR(1), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCCMMNDETAILCODE_PK" PRIMARY KEY ("CODE_ID", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTCCMMNDETAILCODE_FK1" FOREIGN KEY ("CODE_ID")
	  REFERENCES "JOEL"."COMTCCMMNCODE" ("CODE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."CODE_ID" IS '코드ID';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."CODE" IS '코드';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."CODE_NM" IS '코드명';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."CODE_DC" IS '코드설명';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCCMMNDETAILCODE"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTCCMMNDETAILCODE"  IS '공통상세코드';

CREATE TABLE "JOEL"."COMTCZIP" 
   (	"ZIP" VARCHAR2(6) NOT NULL ENABLE, 
	"SN" NUMBER(10,0) NOT NULL ENABLE, 
	"CTPRVN_NM" VARCHAR2(20), 
	"SIGNGU_NM" VARCHAR2(20), 
	"EMD_NM" VARCHAR2(60), 
	"LI_BULD_NM" VARCHAR2(60), 
	"LNBR_DONG_HO" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTCZIP_PK" PRIMARY KEY ("ZIP", "SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTCZIP"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."SN" IS '일련번호';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."CTPRVN_NM" IS '시도명';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."SIGNGU_NM" IS '시군구명';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."EMD_NM" IS '읍면동명';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."LI_BULD_NM" IS '리건물명';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."LNBR_DONG_HO" IS '번지동호';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTCZIP"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTCZIP"  IS '우편번호';

CREATE TABLE "JOEL"."COMTECOPSEQ" 
   (	"TABLE_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"NEXT_ID" NUMBER(30,0), 
	 CONSTRAINT "COMTECOPSEQ_PK" PRIMARY KEY ("TABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTECOPSEQ"."TABLE_NAME" IS '테이블명';
 
   COMMENT ON COLUMN "JOEL"."COMTECOPSEQ"."NEXT_ID" IS '다음아이디';
 
   COMMENT ON TABLE "JOEL"."COMTECOPSEQ"  IS 'COMTECOPSEQ';

CREATE TABLE "JOEL"."COMTHEMAILDSPTCHMANAGE" 
   (	"MSSAGE_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL_CN" CLOB, 
	"SNDR" VARCHAR2(50) NOT NULL ENABLE, 
	"RCVER" VARCHAR2(50) NOT NULL ENABLE, 
	"SJ" VARCHAR2(60) NOT NULL ENABLE, 
	"SNDNG_RESULT_CODE" CHAR(1), 
	"DSPTCH_DT" CHAR(20) NOT NULL ENABLE, 
	"ATCH_FILE_ID" CHAR(20), 
	 CONSTRAINT "COMTHEMAILDSPTCHMANAGE_PK" PRIMARY KEY ("MSSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTHEMAILDSPTCHMANAGE_FK2" FOREIGN KEY ("ATCH_FILE_ID")
	  REFERENCES "JOEL"."COMTNFILE" ("ATCH_FILE_ID") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" 
 LOB ("EMAIL_CN") STORE AS BASICFILE (
  TABLESPACE "TS_PRACTICE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."MSSAGE_ID" IS '메시지ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."EMAIL_CN" IS '이메일내용';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."SNDR" IS '발신자';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."RCVER" IS '수신자';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."SJ" IS '제목';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."SNDNG_RESULT_CODE" IS '발송결과코드';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."DSPTCH_DT" IS '발신일시';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMAILDSPTCHMANAGE"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON TABLE "JOEL"."COMTHEMAILDSPTCHMANAGE"  IS '메일발신관리';

CREATE TABLE "JOEL"."COMTHEMPLYRINFOCHANGEDTLS" 
   (	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CHANGE_DE" CHAR(20), 
	"ORGNZT_ID" CHAR(20), 
	"GROUP_ID" CHAR(20), 
	"EMPL_NO" VARCHAR2(20), 
	"SEXDSTN_CODE" CHAR(1), 
	"BRTHDY" CHAR(20), 
	"FXNUM" VARCHAR2(20), 
	"HOUSE_ADRES" VARCHAR2(100), 
	"HOUSE_END_TELNO" VARCHAR2(4), 
	"AREA_NO" VARCHAR2(4), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"ZIP" VARCHAR2(6), 
	"OFFM_TELNO" VARCHAR2(20), 
	"MBTLNUM" VARCHAR2(20), 
	"EMAIL_ADRES" VARCHAR2(50), 
	"HOUSE_MIDDLE_TELNO" VARCHAR2(4), 
	"PSTINST_CODE" CHAR(8), 
	"EMPLYR_STTUS_CODE" CHAR(1), 
	"ESNTL_ID" CHAR(20), 
	 CONSTRAINT "COMTHEMPLYRINFOCHANGEDTLS_PK" PRIMARY KEY ("EMPLYR_ID", "CHANGE_DE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTHEMPLYRINFOCHANGEDTLS_FK1" FOREIGN KEY ("EMPLYR_ID")
	  REFERENCES "JOEL"."COMTNEMPLYRINFO" ("EMPLYR_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."EMPLYR_ID" IS '업무사용자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."CHANGE_DE" IS '변경일';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."ORGNZT_ID" IS '조직ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."GROUP_ID" IS '그룹ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."EMPL_NO" IS '사원번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."SEXDSTN_CODE" IS '성별코드';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."BRTHDY" IS '생일';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."FXNUM" IS '팩스번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."HOUSE_ADRES" IS '주택주소';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."HOUSE_END_TELNO" IS '주택끝전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."AREA_NO" IS '지역번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."DETAIL_ADRES" IS '상세주소';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."OFFM_TELNO" IS '사무실전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."MBTLNUM" IS '이동전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."EMAIL_ADRES" IS '이메일주소';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."HOUSE_MIDDLE_TELNO" IS '주택중간전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."PSTINST_CODE" IS '소속기관코드';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."EMPLYR_STTUS_CODE" IS '사용자상태코드';
 
   COMMENT ON COLUMN "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"."ESNTL_ID" IS '고유ID';
 
   COMMENT ON TABLE "JOEL"."COMTHEMPLYRINFOCHANGEDTLS"  IS '업무사용자정보변경내역';

CREATE TABLE "JOEL"."COMTHPROGRMCHANGEDTLS" 
   (	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"REQUST_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"RQESTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"CHANGE_REQUST_CN" VARCHAR2(1000), 
	"REQUST_PROCESS_CN" CLOB, 
	"OPETR_ID" VARCHAR2(20), 
	"PROCESS_STTUS_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"PROCESS_DE" CHAR(20), 
	"RQESTDE" CHAR(20), 
	"REQUST_SJ" VARCHAR2(60) NOT NULL ENABLE, 
	 CONSTRAINT "COMTHPROGRMCHANGEDTLS_PK" PRIMARY KEY ("PROGRM_FILE_NM", "REQUST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTHPROGRMCHANGEDTLS_FK1" FOREIGN KEY ("PROGRM_FILE_NM")
	  REFERENCES "JOEL"."COMTNPROGRMLIST" ("PROGRM_FILE_NM") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" 
 LOB ("REQUST_PROCESS_CN") STORE AS BASICFILE (
  TABLESPACE "TS_PRACTICE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."PROGRM_FILE_NM" IS '프로그램파일명';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."REQUST_NO" IS '요청번호';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."RQESTER_ID" IS '요청자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."CHANGE_REQUST_CN" IS '변경요청내용';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."REQUST_PROCESS_CN" IS '요청처리내용';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."OPETR_ID" IS '처리자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."PROCESS_STTUS_CODE" IS '처리상태코드';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."PROCESS_DE" IS '처리일';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."RQESTDE" IS '요청일';
 
   COMMENT ON COLUMN "JOEL"."COMTHPROGRMCHANGEDTLS"."REQUST_SJ" IS '요청제목';
 
   COMMENT ON TABLE "JOEL"."COMTHPROGRMCHANGEDTLS"  IS '프로그램변경내역';

CREATE TABLE "JOEL"."COMTHSYSHIST" 
   (	"HIST_ID" CHAR(20) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"HIST_SE_CODE" CHAR(6) NOT NULL ENABLE, 
	"HIST_CN" VARCHAR2(2500) NOT NULL ENABLE, 
	"SYS_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"ATCH_FILE_ID" CHAR(20), 
	 CONSTRAINT "COMTHSYSHIST_PK" PRIMARY KEY ("HIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."HIST_ID" IS '이력ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."HIST_SE_CODE" IS '이력구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."HIST_CN" IS '이력내용';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."SYS_NM" IS '시스템명';
 
   COMMENT ON COLUMN "JOEL"."COMTHSYSHIST"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON TABLE "JOEL"."COMTHSYSHIST"  IS '시스템이력';

CREATE TABLE "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO" 
   (	"LOG_ID" CHAR(20) NOT NULL ENABLE, 
	"CNTC_ID" CHAR(8) NOT NULL ENABLE, 
	"TEST_CLASS_NM" VARCHAR2(255), 
	"MNGR_NM" VARCHAR2(60), 
	"MNGR_EMAIL_ADRES" VARCHAR2(50), 
	"MNTRNG_STTUS" CHAR(2), 
	"LOG_INFO" VARCHAR2(2000), 
	"CREAT_DT" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE NOT NULL ENABLE, 
	 CONSTRAINT "COMTHTRSMRCVMNTRNGLOGINFO_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."LOG_ID" IS '로그ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."CNTC_ID" IS '연계ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."TEST_CLASS_NM" IS '테스트클래스명';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."MNGR_NM" IS '관리자명';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."MNGR_EMAIL_ADRES" IS '관리자이메일주소';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."MNTRNG_STTUS" IS '모니터링상태';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."LOG_INFO" IS '로그정보';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."CREAT_DT" IS '생성일시';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON TABLE "JOEL"."COMTHTRSMRCVMNTRNGLOGINFO"  IS '송수신모니터링로그정보';

CREATE TABLE "JOEL"."COMTNAUTHORGROUPINFO" 
   (	"GROUP_ID" CHAR(20) NOT NULL ENABLE, 
	"GROUP_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"GROUP_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	"GROUP_DC" VARCHAR2(100), 
	 CONSTRAINT "COMTNAUTHORGROUPINFO_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNAUTHORGROUPINFO"."GROUP_ID" IS '그룹ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORGROUPINFO"."GROUP_NM" IS '그룹명';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORGROUPINFO"."GROUP_CREAT_DE" IS '그룹생성일';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORGROUPINFO"."GROUP_DC" IS '그룹설명';
 
   COMMENT ON TABLE "JOEL"."COMTNAUTHORGROUPINFO"  IS '권한그룹정보';

CREATE TABLE "JOEL"."COMTNAUTHORINFO" 
   (	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"AUTHOR_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"AUTHOR_DC" VARCHAR2(200), 
	"AUTHOR_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNAUTHORINFO_PK" PRIMARY KEY ("AUTHOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNAUTHORINFO"."AUTHOR_CODE" IS '권한코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORINFO"."AUTHOR_NM" IS '권한명';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORINFO"."AUTHOR_DC" IS '권한설명';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORINFO"."AUTHOR_CREAT_DE" IS '권한생성일';
 
   COMMENT ON TABLE "JOEL"."COMTNAUTHORINFO"  IS '권한정보';

CREATE TABLE "JOEL"."COMTNAUTHORROLERELATE" 
   (	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"CREAT_DT" DATE, 
	 CONSTRAINT "COMTNAUTHORROLERELATE_PK" PRIMARY KEY ("AUTHOR_CODE", "ROLE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNAUTHORROLERELATE_FK1" FOREIGN KEY ("AUTHOR_CODE")
	  REFERENCES "JOEL"."COMTNAUTHORINFO" ("AUTHOR_CODE") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMTNAUTHORROLERELATE_FK2" FOREIGN KEY ("ROLE_CODE")
	  REFERENCES "JOEL"."COMTNROLEINFO" ("ROLE_CODE") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNAUTHORROLERELATE"."AUTHOR_CODE" IS '권한코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORROLERELATE"."ROLE_CODE" IS '롤코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNAUTHORROLERELATE"."CREAT_DT" IS '생성일시';
 
   COMMENT ON TABLE "JOEL"."COMTNAUTHORROLERELATE"  IS '권한롤관계';

CREATE TABLE "JOEL"."COMTNBBS" 
   (	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(20) NOT NULL ENABLE, 
	"NTT_NO" NUMBER(20,0), 
	"NTT_SJ" VARCHAR2(2000), 
	"NTT_CN" CLOB, 
	"ANSWER_AT" CHAR(1), 
	"PARNTSCTT_NO" NUMBER(10,0), 
	"ANSWER_LC" NUMBER(8,0), 
	"SORT_ORDR" NUMBER(8,0), 
	"RDCNT" NUMBER(10,0), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"NTCE_BGNDE" CHAR(20), 
	"NTCE_ENDDE" CHAR(20), 
	"NTCR_ID" VARCHAR2(20), 
	"NTCR_NM" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(200), 
	"ATCH_FILE_ID" CHAR(20), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNBBS_PK" PRIMARY KEY ("NTT_ID", "BBS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNBBS_FK1" FOREIGN KEY ("BBS_ID")
	  REFERENCES "JOEL"."COMTNBBSMASTER" ("BBS_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" 
 LOB ("NTT_CN") STORE AS BASICFILE (
  TABLESPACE "TS_PRACTICE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTT_ID" IS '게시물ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTT_NO" IS '게시물번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTT_SJ" IS '게시물제목';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTT_CN" IS '게시물내용';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."ANSWER_AT" IS '댓글여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."PARNTSCTT_NO" IS '부모글번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."ANSWER_LC" IS '댓글위치';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."SORT_ORDR" IS '정렬순서';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."RDCNT" IS '조회수';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTCE_BGNDE" IS '게시시작일';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTCE_ENDDE" IS '게시종료일';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTCR_ID" IS '게시자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."NTCR_NM" IS '게시자명';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBS"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNBBS"  IS '게시판';

CREATE TABLE "JOEL"."COMTNBBSMASTER" 
   (	"BBS_ID" CHAR(20) NOT NULL ENABLE, 
	"BBS_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"BBS_INTRCN" VARCHAR2(2400), 
	"BBS_TY_CODE" CHAR(6) NOT NULL ENABLE, 
	"BBS_ATTRB_CODE" CHAR(6) NOT NULL ENABLE, 
	"REPLY_POSBL_AT" CHAR(1), 
	"FILE_ATCH_POSBL_AT" CHAR(1) NOT NULL ENABLE, 
	"ATCH_POSBL_FILE_NUMBER" NUMBER(2,0) NOT NULL ENABLE, 
	"ATCH_POSBL_FILE_SIZE" NUMBER(8,0), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"TMPLAT_ID" CHAR(20), 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	 CONSTRAINT "COMTNBBSMASTER_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."BBS_NM" IS '게시판명';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."BBS_INTRCN" IS '게시판소개';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."BBS_TY_CODE" IS '게시판유형코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."BBS_ATTRB_CODE" IS '게시판속성코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."REPLY_POSBL_AT" IS '답장가능여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."FILE_ATCH_POSBL_AT" IS '파일첨부가능여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."ATCH_POSBL_FILE_NUMBER" IS '첨부가능파일숫자';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."ATCH_POSBL_FILE_SIZE" IS '첨부가능파일사이즈';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."TMPLAT_ID" IS '템플릿ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTER"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON TABLE "JOEL"."COMTNBBSMASTER"  IS '게시판마스터';

CREATE TABLE "JOEL"."COMTNBBSMASTEROPTN" 
   (	"BBS_ID" CHAR(20) NOT NULL ENABLE, 
	"ANSWER_AT" CHAR(1) NOT NULL ENABLE, 
	"STSFDG_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNBBSMASTEROPTN_PK" PRIMARY KEY ("BBS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."ANSWER_AT" IS '댓글여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."STSFDG_AT" IS '만족도여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSMASTEROPTN"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNBBSMASTEROPTN"  IS '게시판마스터옵션';

CREATE TABLE "JOEL"."COMTNBBSUSE" 
   (	"BBS_ID" CHAR(20) NOT NULL ENABLE, 
	"TRGET_ID" CHAR(20) NOT NULL ENABLE, 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"REGIST_SE_CODE" CHAR(6), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNBBSUSE_PK" PRIMARY KEY ("BBS_ID", "TRGET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNBBSUSE_FK1" FOREIGN KEY ("BBS_ID")
	  REFERENCES "JOEL"."COMTNBBSMASTER" ("BBS_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."TRGET_ID" IS '대상ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."REGIST_SE_CODE" IS '등록구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNBBSUSE"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNBBSUSE"  IS '게시판활용';

CREATE TABLE "JOEL"."COMTNBKMKMENUMANAGERESULT" 
   (	"MENU_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MENU_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_STRE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNBKMKMENUMANAGERESULT_PK" PRIMARY KEY ("MENU_ID", "EMPLYR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNBKMKMENUMANAGERESULT"."MENU_ID" IS '메뉴ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBKMKMENUMANAGERESULT"."EMPLYR_ID" IS '업무사용자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNBKMKMENUMANAGERESULT"."MENU_NM" IS '메뉴명';
 
   COMMENT ON COLUMN "JOEL"."COMTNBKMKMENUMANAGERESULT"."PROGRM_STRE_PATH" IS '프로그램저장경로';
 
   COMMENT ON TABLE "JOEL"."COMTNBKMKMENUMANAGERESULT"  IS '바로가기 메뉴 등록';

CREATE TABLE "JOEL"."COMTNCLUB" 
   (	"CLB_ID" CHAR(20) NOT NULL ENABLE, 
	"CMMNTY_ID" CHAR(20) NOT NULL ENABLE, 
	"CLB_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"CLB_INTRCN" VARCHAR2(2400), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"REGIST_SE_CODE" CHAR(6), 
	"TMPLAT_ID" CHAR(20), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNCLUB_PK" PRIMARY KEY ("CLB_ID", "CMMNTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."CLB_ID" IS '동호회ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."CMMNTY_ID" IS '커뮤니티ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."CLB_NM" IS '동호회명';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."CLB_INTRCN" IS '동호회소개';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."REGIST_SE_CODE" IS '등록구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."TMPLAT_ID" IS '템플릿ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCLUB"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNCLUB"  IS '동호회속성';

CREATE TABLE "JOEL"."COMTNCMMNTY" 
   (	"CMMNTY_ID" CHAR(20) NOT NULL ENABLE, 
	"CMMNTY_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"CMMNTY_INTRCN" VARCHAR2(2400), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"REGIST_SE_CODE" CHAR(6), 
	"TMPLAT_ID" CHAR(20), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNCMMNTY_PK" PRIMARY KEY ("CMMNTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."CMMNTY_ID" IS '커뮤니티ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."CMMNTY_NM" IS '커뮤니티명';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."CMMNTY_INTRCN" IS '커뮤니티소개';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."REGIST_SE_CODE" IS '등록구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."TMPLAT_ID" IS '템플릿ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCMMNTY"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNCMMNTY"  IS '커뮤니티 속성';

CREATE TABLE "JOEL"."COMTNCNTCINSTT" 
   (	"INSTT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"INSTT_NM" VARCHAR2(100), 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDT_PNTTM" DATE, 
	"USE_AT" CHAR(1), 
	 CONSTRAINT "COMTNCNTCINSTT_PK" PRIMARY KEY ("INSTT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."INSTT_ID" IS '기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."INSTT_NM" IS '기관명';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCINSTT"."USE_AT" IS '사용여부';
 
   COMMENT ON TABLE "JOEL"."COMTNCNTCINSTT"  IS '연계기관';

CREATE TABLE "JOEL"."COMTNCNTCSERVICE" 
   (	"INSTT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SYS_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SVC_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255), 
	"REQUST_MSSAGE_ID" VARCHAR2(20), 
	"RSPNS_MSSAGE_ID" VARCHAR2(20), 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"USE_AT" CHAR(1), 
	 CONSTRAINT "COMTNCNTCSERVICE_PK" PRIMARY KEY ("INSTT_ID", "SYS_ID", "SVC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."INSTT_ID" IS '기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."SYS_ID" IS '시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."SVC_ID" IS '서비스ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."SVC_NM" IS '서비스명';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."REQUST_MSSAGE_ID" IS '요청메시지ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."RSPNS_MSSAGE_ID" IS '응답메시지ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSERVICE"."USE_AT" IS '사용여부';
 
   COMMENT ON TABLE "JOEL"."COMTNCNTCSERVICE"  IS '연계서비스';

CREATE TABLE "JOEL"."COMTNCNTCSYSTEM" 
   (	"INSTT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SYS_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SYS_NM" VARCHAR2(255), 
	"SYS_IP" VARCHAR2(23), 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"USE_AT" CHAR(1), 
	 CONSTRAINT "COMTNCNTCSYSTEM_PK" PRIMARY KEY ("INSTT_ID", "SYS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."INSTT_ID" IS '기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."SYS_ID" IS '시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."SYS_NM" IS '시스템명';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."SYS_IP" IS '시스템IP';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCNTCSYSTEM"."USE_AT" IS '사용여부';
 
   COMMENT ON TABLE "JOEL"."COMTNCNTCSYSTEM"  IS '연계시스템';

CREATE TABLE "JOEL"."COMTNCOMMENT" 
   (	"NTT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BBS_ID" CHAR(20) NOT NULL ENABLE, 
	"ANSWER_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"WRTER_ID" VARCHAR2(20), 
	"WRTER_NM" VARCHAR2(20), 
	"ANSWER" VARCHAR2(200), 
	"USE_AT" CHAR(1) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"FRST_REGISTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(200), 
	 CONSTRAINT "COMTNCOMMENT_PK" PRIMARY KEY ("NTT_ID", "BBS_ID", "ANSWER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNCOMMENT_FK1" FOREIGN KEY ("NTT_ID", "BBS_ID")
	  REFERENCES "JOEL"."COMTNBBS" ("NTT_ID", "BBS_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."NTT_ID" IS '게시물ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."BBS_ID" IS '게시판ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."ANSWER_NO" IS '댓글번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."WRTER_ID" IS '작성자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."WRTER_NM" IS '작성자명';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."ANSWER" IS '댓글';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNCOMMENT"."PASSWORD" IS '비밀번호';
 
   COMMENT ON TABLE "JOEL"."COMTNCOMMENT"  IS '댓글';

CREATE TABLE "JOEL"."COMTNEMPLYRINFO" 
   (	"EMPLYR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGNZT_ID" CHAR(20), 
	"USER_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"EMPL_NO" VARCHAR2(20), 
	"IHIDNUM" VARCHAR2(200), 
	"SEXDSTN_CODE" CHAR(1), 
	"BRTHDY" CHAR(20), 
	"FXNUM" VARCHAR2(20), 
	"HOUSE_ADRES" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORD_HINT" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORD_CNSR" VARCHAR2(100) NOT NULL ENABLE, 
	"HOUSE_END_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"AREA_NO" VARCHAR2(4) NOT NULL ENABLE, 
	"DETAIL_ADRES" VARCHAR2(100), 
	"ZIP" VARCHAR2(6) NOT NULL ENABLE, 
	"OFFM_TELNO" VARCHAR2(20), 
	"MBTLNUM" VARCHAR2(20), 
	"EMAIL_ADRES" VARCHAR2(50), 
	"OFCPS_NM" VARCHAR2(60), 
	"HOUSE_MIDDLE_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"GROUP_ID" CHAR(20), 
	"PSTINST_CODE" CHAR(8), 
	"EMPLYR_STTUS_CODE" CHAR(1) NOT NULL ENABLE, 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	"CRTFC_DN_VALUE" VARCHAR2(100), 
	"SBSCRB_DE" DATE, 
	 CONSTRAINT "COMTNEMPLYRINFO_PK" PRIMARY KEY ("EMPLYR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNEMPLYRINFO_FK2" FOREIGN KEY ("ORGNZT_ID")
	  REFERENCES "JOEL"."COMTNORGNZTINFO" ("ORGNZT_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMTNEMPLYRINFO_FK1" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "JOEL"."COMTNAUTHORGROUPINFO" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."EMPLYR_ID" IS '업무사용자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."ORGNZT_ID" IS '조직ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."USER_NM" IS '사용자명';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."EMPL_NO" IS '사원번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."IHIDNUM" IS '주민등록번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."SEXDSTN_CODE" IS '성별코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."BRTHDY" IS '생일';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."FXNUM" IS '팩스번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."HOUSE_ADRES" IS '주택주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."PASSWORD_HINT" IS '비밀번호힌트';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."PASSWORD_CNSR" IS '비밀번호정답';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."HOUSE_END_TELNO" IS '주택끝전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."AREA_NO" IS '지역번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."DETAIL_ADRES" IS '상세주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."OFFM_TELNO" IS '사무실전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."MBTLNUM" IS '이동전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."EMAIL_ADRES" IS '이메일주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."OFCPS_NM" IS '직위명';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."HOUSE_MIDDLE_TELNO" IS '주택중간전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."GROUP_ID" IS '그룹ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."PSTINST_CODE" IS '소속기관코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."EMPLYR_STTUS_CODE" IS '사용자상태코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."ESNTL_ID" IS '고유ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."CRTFC_DN_VALUE" IS '인증DN값';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRINFO"."SBSCRB_DE" IS '가입일자';
 
   COMMENT ON TABLE "JOEL"."COMTNEMPLYRINFO"  IS '업무사용자정보';

CREATE TABLE "JOEL"."COMTNEMPLYRSCRTYESTBS" 
   (	"SCRTY_DTRMN_TRGET_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MBER_TY_CODE" CHAR(5), 
	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRSCRTYESTBS"."SCRTY_DTRMN_TRGET_ID" IS '보안설정대상ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRSCRTYESTBS"."MBER_TY_CODE" IS '회원유형코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNEMPLYRSCRTYESTBS"."AUTHOR_CODE" IS '권한코드';
 
   COMMENT ON TABLE "JOEL"."COMTNEMPLYRSCRTYESTBS"  IS '사용자보안설정';

CREATE TABLE "JOEL"."COMTNENTRPRSMBER" 
   (	"ENTRPRS_MBER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ENTRPRS_SE_CODE" CHAR(8), 
	"BIZRNO" VARCHAR2(10), 
	"JURIRNO" VARCHAR2(13), 
	"CMPNY_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CXFC" VARCHAR2(50), 
	"ZIP" VARCHAR2(6) NOT NULL ENABLE, 
	"ADRES" VARCHAR2(100) NOT NULL ENABLE, 
	"ENTRPRS_MIDDLE_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"FXNUM" VARCHAR2(20), 
	"INDUTY_CODE" CHAR(1), 
	"APPLCNT_NM" VARCHAR2(50) NOT NULL ENABLE, 
	"APPLCNT_IHIDNUM" VARCHAR2(200), 
	"SBSCRB_DE" DATE, 
	"ENTRPRS_MBER_STTUS" VARCHAR2(15), 
	"ENTRPRS_MBER_PASSWORD" VARCHAR2(200), 
	"ENTRPRS_MBER_PASSWORD_HINT" VARCHAR2(100) NOT NULL ENABLE, 
	"ENTRPRS_MBER_PASSWORD_CNSR" VARCHAR2(100) NOT NULL ENABLE, 
	"GROUP_ID" CHAR(20), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"ENTRPRS_END_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"AREA_NO" VARCHAR2(4) NOT NULL ENABLE, 
	"APPLCNT_EMAIL_ADRES" VARCHAR2(50) NOT NULL ENABLE, 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNENTRPRSMBER_PK" PRIMARY KEY ("ENTRPRS_MBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNENTRPRSMBER_FK1" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "JOEL"."COMTNAUTHORGROUPINFO" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_MBER_ID" IS '기업회원ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_SE_CODE" IS '기업구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."BIZRNO" IS '사업자등록번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."JURIRNO" IS '법인등록번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."CMPNY_NM" IS '회사명';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."CXFC" IS '대표이사';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ADRES" IS '주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_MIDDLE_TELNO" IS '기업중간전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."FXNUM" IS '팩스번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."INDUTY_CODE" IS '업종코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."APPLCNT_NM" IS '신청인명';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."APPLCNT_IHIDNUM" IS '신청인주민등록번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."SBSCRB_DE" IS '가입일자';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_MBER_STTUS" IS '기업회원상태';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_MBER_PASSWORD" IS '기업회원비밀번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_MBER_PASSWORD_HINT" IS '기업회원비밀번호힌트';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_MBER_PASSWORD_CNSR" IS '기업회원비밀번호정답';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."GROUP_ID" IS '그룹ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."DETAIL_ADRES" IS '상세주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ENTRPRS_END_TELNO" IS '기업끝전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."AREA_NO" IS '지역번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."APPLCNT_EMAIL_ADRES" IS '신청자이메일주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNENTRPRSMBER"."ESNTL_ID" IS '고유ID';
 
   COMMENT ON TABLE "JOEL"."COMTNENTRPRSMBER"  IS '기업회원';

CREATE TABLE "JOEL"."COMTNFILE" 
   (	"ATCH_FILE_ID" CHAR(20) NOT NULL ENABLE, 
	"CREAT_DT" DATE NOT NULL ENABLE, 
	"USE_AT" CHAR(1), 
	 CONSTRAINT "COMTNFILE_PK" PRIMARY KEY ("ATCH_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNFILE"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILE"."CREAT_DT" IS '생성일시';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILE"."USE_AT" IS '사용여부';
 
   COMMENT ON TABLE "JOEL"."COMTNFILE"  IS '파일속성';

CREATE TABLE "JOEL"."COMTNFILEDETAIL" 
   (	"ATCH_FILE_ID" CHAR(20) NOT NULL ENABLE, 
	"FILE_SN" NUMBER(10,0) NOT NULL ENABLE, 
	"FILE_STRE_COURS" VARCHAR2(2000) NOT NULL ENABLE, 
	"STRE_FILE_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"ORIGNL_FILE_NM" VARCHAR2(255), 
	"FILE_EXTSN" VARCHAR2(20) NOT NULL ENABLE, 
	"FILE_CN" CLOB, 
	"FILE_SIZE" NUMBER(8,0), 
	 CONSTRAINT "COMTNFILEDETAIL_PK" PRIMARY KEY ("ATCH_FILE_ID", "FILE_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNFILEDETAIL_FK1" FOREIGN KEY ("ATCH_FILE_ID")
	  REFERENCES "JOEL"."COMTNFILE" ("ATCH_FILE_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" 
 LOB ("FILE_CN") STORE AS BASICFILE (
  TABLESPACE "TS_PRACTICE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."ATCH_FILE_ID" IS '첨부파일ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."FILE_SN" IS '파일순번';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."FILE_STRE_COURS" IS '파일저장경로';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."STRE_FILE_NM" IS '저장파일명';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."ORIGNL_FILE_NM" IS '원파일명';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."FILE_EXTSN" IS '파일확장자';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."FILE_CN" IS '파일내용';
 
   COMMENT ON COLUMN "JOEL"."COMTNFILEDETAIL"."FILE_SIZE" IS '파일크기';
 
   COMMENT ON TABLE "JOEL"."COMTNFILEDETAIL"  IS '파일상세정보';

CREATE TABLE "JOEL"."COMTNGNRLMBER" 
   (	"MBER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"PASSWORD_HINT" VARCHAR2(100), 
	"PASSWORD_CNSR" VARCHAR2(100), 
	"IHIDNUM" VARCHAR2(200), 
	"MBER_NM" VARCHAR2(50) NOT NULL ENABLE, 
	"ZIP" VARCHAR2(6) NOT NULL ENABLE, 
	"ADRES" VARCHAR2(100) NOT NULL ENABLE, 
	"AREA_NO" VARCHAR2(4) NOT NULL ENABLE, 
	"MBER_STTUS" VARCHAR2(15), 
	"DETAIL_ADRES" VARCHAR2(100), 
	"END_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"MBTLNUM" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" CHAR(20), 
	"MBER_FXNUM" VARCHAR2(20), 
	"MBER_EMAIL_ADRES" VARCHAR2(50), 
	"MIDDLE_TELNO" VARCHAR2(4) NOT NULL ENABLE, 
	"SBSCRB_DE" DATE, 
	"SEXDSTN_CODE" CHAR(1), 
	"ESNTL_ID" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNGNRLMBER_PK" PRIMARY KEY ("MBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNGNRLMBER_FK1" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "JOEL"."COMTNAUTHORGROUPINFO" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MBER_ID" IS '회원ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."PASSWORD_HINT" IS '비밀번호힌트';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."PASSWORD_CNSR" IS '비밀번호정답';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."IHIDNUM" IS '주민등록번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MBER_NM" IS '회원명';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."ADRES" IS '주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."AREA_NO" IS '지역번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MBER_STTUS" IS '회원상태';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."DETAIL_ADRES" IS '상세주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."END_TELNO" IS '끝전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MBTLNUM" IS '이동전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."GROUP_ID" IS '그룹ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MBER_FXNUM" IS '회원팩스번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MBER_EMAIL_ADRES" IS '회원이메일주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."MIDDLE_TELNO" IS '중간전화번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."SBSCRB_DE" IS '가입일자';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."SEXDSTN_CODE" IS '성별코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNGNRLMBER"."ESNTL_ID" IS '고유ID';
 
   COMMENT ON TABLE "JOEL"."COMTNGNRLMBER"  IS '일반회원';

CREATE TABLE "JOEL"."COMTNLOGINLOG" 
   (	"LOG_ID" CHAR(20) NOT NULL ENABLE, 
	"CONECT_ID" VARCHAR2(20), 
	"CONECT_IP" VARCHAR2(23), 
	"CONECT_MTHD" CHAR(4), 
	"ERROR_OCCRRNC_AT" CHAR(1), 
	"ERROR_CODE" CHAR(3), 
	"CREAT_DT" DATE, 
	 CONSTRAINT "COMTNLOGINLOG_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."LOG_ID" IS '로그ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."CONECT_ID" IS '접속ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."CONECT_IP" IS '접속IP';
 
   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."CONECT_MTHD" IS '접속방식';
 
   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."ERROR_OCCRRNC_AT" IS '오류발생여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."ERROR_CODE" IS '오류코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNLOGINLOG"."CREAT_DT" IS '생성일시';
 
   COMMENT ON TABLE "JOEL"."COMTNLOGINLOG"  IS '접속로그';

CREATE TABLE "JOEL"."COMTNMENUCREATDTLS" 
   (	"MENU_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"AUTHOR_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"MAPNG_CREAT_ID" VARCHAR2(30), 
	 CONSTRAINT "COMTNMENUCREATDTLS_PK" PRIMARY KEY ("MENU_NO", "AUTHOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNMENUCREATDTLS_FK2" FOREIGN KEY ("MENU_NO")
	  REFERENCES "JOEL"."COMTNMENUINFO" ("MENU_NO") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMTNMENUCREATDTLS_FK3" FOREIGN KEY ("MAPNG_CREAT_ID")
	  REFERENCES "JOEL"."COMTNSITEMAP" ("MAPNG_CREAT_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMTNMENUCREATDTLS_FK1" FOREIGN KEY ("AUTHOR_CODE")
	  REFERENCES "JOEL"."COMTNAUTHORINFO" ("AUTHOR_CODE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNMENUCREATDTLS"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUCREATDTLS"."AUTHOR_CODE" IS '권한코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUCREATDTLS"."MAPNG_CREAT_ID" IS '매핑생성ID';
 
   COMMENT ON TABLE "JOEL"."COMTNMENUCREATDTLS"  IS '메뉴생성내역';

CREATE TABLE "JOEL"."COMTNMENUINFO" 
   (	"MENU_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"MENU_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"UPPER_MENU_NO" NUMBER(20,0), 
	"MENU_ORDR" NUMBER(5,0) NOT NULL ENABLE, 
	"MENU_DC" VARCHAR2(250), 
	"RELATE_IMAGE_PATH" VARCHAR2(100), 
	"RELATE_IMAGE_NM" VARCHAR2(60), 
	 CONSTRAINT "COMTNMENUINFO_PK" PRIMARY KEY ("MENU_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNMENUINFO_FK2" FOREIGN KEY ("PROGRM_FILE_NM")
	  REFERENCES "JOEL"."COMTNPROGRMLIST" ("PROGRM_FILE_NM") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMTNMENUINFO_FK1" FOREIGN KEY ("UPPER_MENU_NO")
	  REFERENCES "JOEL"."COMTNMENUINFO" ("MENU_NO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."MENU_NM" IS '메뉴명';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."PROGRM_FILE_NM" IS '프로그램파일명';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."MENU_NO" IS '메뉴번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."UPPER_MENU_NO" IS '상위메뉴번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."MENU_ORDR" IS '메뉴순서';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."MENU_DC" IS '메뉴설명';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."RELATE_IMAGE_PATH" IS '관계이미지경로';
 
   COMMENT ON COLUMN "JOEL"."COMTNMENUINFO"."RELATE_IMAGE_NM" IS '관계이미지명';
 
   COMMENT ON TABLE "JOEL"."COMTNMENUINFO"  IS '메뉴정보';

CREATE TABLE "JOEL"."COMTNORGNZTINFO" 
   (	"ORGNZT_ID" CHAR(20) NOT NULL ENABLE, 
	"ORGNZT_NM" VARCHAR2(20) NOT NULL ENABLE, 
	"ORGNZT_DC" VARCHAR2(100), 
	 CONSTRAINT "COMTNORGNZTINFO_PK" PRIMARY KEY ("ORGNZT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNORGNZTINFO"."ORGNZT_ID" IS '조직ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNORGNZTINFO"."ORGNZT_NM" IS '조직명';
 
   COMMENT ON COLUMN "JOEL"."COMTNORGNZTINFO"."ORGNZT_DC" IS '조직설명';
 
   COMMENT ON TABLE "JOEL"."COMTNORGNZTINFO"  IS '조직정보';

CREATE TABLE "JOEL"."COMTNPRIVACYLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"INQIRE_DT" DATE NOT NULL ENABLE, 
	"SRVC_NM" VARCHAR2(500), 
	"INQIRE_INFO" VARCHAR2(100), 
	"RQESTER_ID" VARCHAR2(20), 
	"RQESTER_IP" VARCHAR2(23), 
	 CONSTRAINT "REQUST_ID_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;

CREATE TABLE "JOEL"."COMTNPROGRMLIST" 
   (	"PROGRM_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"PROGRM_STRE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	"PROGRM_KOREAN_NM" VARCHAR2(60), 
	"PROGRM_DC" VARCHAR2(200), 
	"URL" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNPROGRMLIST_PK" PRIMARY KEY ("PROGRM_FILE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNPROGRMLIST"."PROGRM_FILE_NM" IS '프로그램파일명';
 
   COMMENT ON COLUMN "JOEL"."COMTNPROGRMLIST"."PROGRM_STRE_PATH" IS '프로그램저장경로';
 
   COMMENT ON COLUMN "JOEL"."COMTNPROGRMLIST"."PROGRM_KOREAN_NM" IS '프로그램한글명';
 
   COMMENT ON COLUMN "JOEL"."COMTNPROGRMLIST"."PROGRM_DC" IS '프로그램설명';
 
   COMMENT ON COLUMN "JOEL"."COMTNPROGRMLIST"."URL" IS 'URL';
 
   COMMENT ON TABLE "JOEL"."COMTNPROGRMLIST"  IS '프로그램목록';

CREATE TABLE "JOEL"."COMTNRESTDE" 
   (	"RESTDE_NO" NUMBER(6,0) NOT NULL ENABLE, 
	"RESTDE" CHAR(8), 
	"RESTDE_NM" VARCHAR2(60), 
	"RESTDE_DC" VARCHAR2(200), 
	"RESTDE_SE_CODE" VARCHAR2(2), 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNRESTDE_PK" PRIMARY KEY ("RESTDE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."RESTDE_NO" IS '휴일번호';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."RESTDE" IS '휴일';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."RESTDE_NM" IS '휴일명';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."RESTDE_DC" IS '휴일설명';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."RESTDE_SE_CODE" IS '휴일구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNRESTDE"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNRESTDE"  IS '휴일관리';

CREATE TABLE "JOEL"."COMTNROLEINFO" 
   (	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"ROLE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"ROLE_PTTRN" VARCHAR2(300), 
	"ROLE_DC" VARCHAR2(200), 
	"ROLE_TY" VARCHAR2(80), 
	"ROLE_SORT" VARCHAR2(10), 
	"ROLE_CREAT_DE" CHAR(20) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNROLEINFO_PK" PRIMARY KEY ("ROLE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_CODE" IS '롤코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_NM" IS '롤명';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_PTTRN" IS '롤패턴';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_DC" IS '롤설명';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_TY" IS '롤유형';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_SORT" IS '롤정렬';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLEINFO"."ROLE_CREAT_DE" IS '롤생성일';
 
   COMMENT ON TABLE "JOEL"."COMTNROLEINFO"  IS '롤정보';

CREATE TABLE "JOEL"."COMTNROLES_HIERARCHY" 
   (	"PARNTS_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	"CHLDRN_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNROLES_HIERARCHY_PK" PRIMARY KEY ("PARNTS_ROLE", "CHLDRN_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE, 
	 CONSTRAINT "COMTNROLES_HIERARCHY_FK1" FOREIGN KEY ("PARNTS_ROLE")
	  REFERENCES "JOEL"."COMTNAUTHORINFO" ("AUTHOR_CODE") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COMTNROLES_HIERARCHY_FK2" FOREIGN KEY ("CHLDRN_ROLE")
	  REFERENCES "JOEL"."COMTNAUTHORINFO" ("AUTHOR_CODE") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNROLES_HIERARCHY"."PARNTS_ROLE" IS '부모롤';
 
   COMMENT ON COLUMN "JOEL"."COMTNROLES_HIERARCHY"."CHLDRN_ROLE" IS '자식롤';
 
   COMMENT ON TABLE "JOEL"."COMTNROLES_HIERARCHY"  IS '롤 계층구조';

CREATE TABLE "JOEL"."COMTNSITEMAP" 
   (	"MAPNG_CREAT_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"MAPNG_FILE_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"MAPNG_FILE_PATH" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "COMTNSITEMAP_PK" PRIMARY KEY ("MAPNG_CREAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNSITEMAP"."MAPNG_CREAT_ID" IS '매핑생성ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSITEMAP"."CREATR_ID" IS '생성자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSITEMAP"."MAPNG_FILE_NM" IS '매핑파일명';
 
   COMMENT ON COLUMN "JOEL"."COMTNSITEMAP"."MAPNG_FILE_PATH" IS '매핑파일경로';
 
   COMMENT ON TABLE "JOEL"."COMTNSITEMAP"  IS '사이트맵';

CREATE TABLE "JOEL"."COMTNSTPLATINFO" 
   (	"USE_STPLAT_ID" CHAR(20) NOT NULL ENABLE, 
	"USE_STPLAT_NM" VARCHAR2(100), 
	"USE_STPLAT_CN" CLOB, 
	"INFO_PROVD_AGRE_CN" CLOB, 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNSTPLATINFO_PK" PRIMARY KEY ("USE_STPLAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" 
 LOB ("USE_STPLAT_CN") STORE AS BASICFILE (
  TABLESPACE "TS_PRACTICE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INFO_PROVD_AGRE_CN") STORE AS BASICFILE (
  TABLESPACE "TS_PRACTICE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."USE_STPLAT_ID" IS '이용약관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."USE_STPLAT_NM" IS '이용약관명';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."USE_STPLAT_CN" IS '이용약관내용';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."INFO_PROVD_AGRE_CN" IS '정보제공동의내용';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNSTPLATINFO"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNSTPLATINFO"  IS '약관정보';

CREATE TABLE "JOEL"."COMTNSYSLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"JOB_SE_CODE" CHAR(3), 
	"INSTT_CODE" CHAR(7), 
	"OCCRRNC_DE" CHAR(20), 
	"RQESTER_IP" VARCHAR2(23), 
	"RQESTER_ID" VARCHAR2(20), 
	"TRGET_MENU_NM" VARCHAR2(255), 
	"SVC_NM" VARCHAR2(255), 
	"METHOD_NM" VARCHAR2(60), 
	"PROCESS_SE_CODE" CHAR(3), 
	"PROCESS_CO" NUMBER(10,0), 
	"PROCESS_TIME" VARCHAR2(14), 
	"RSPNS_CODE" CHAR(3), 
	"ERROR_SE" CHAR(1), 
	"ERROR_CO" NUMBER(10,0), 
	"ERROR_CODE" CHAR(3), 
	 CONSTRAINT "COMTNSYSLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."REQUST_ID" IS '요청ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."JOB_SE_CODE" IS '업무구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."INSTT_CODE" IS '기관코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."RQESTER_IP" IS '요청자IP';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."RQESTER_ID" IS '요청자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."TRGET_MENU_NM" IS '대상메뉴명';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."SVC_NM" IS '서비스명';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."METHOD_NM" IS '메서드명';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."PROCESS_SE_CODE" IS '처리구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."PROCESS_CO" IS '처리수';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."PROCESS_TIME" IS '처리시간';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."RSPNS_CODE" IS '응답코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."ERROR_SE" IS '오류구분';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."ERROR_CO" IS '오류수';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSLOG"."ERROR_CODE" IS '오류코드';
 
   COMMENT ON TABLE "JOEL"."COMTNSYSLOG"  IS '시스템로그';

CREATE TABLE "JOEL"."COMTNSYSTEMCNTC" 
   (	"CNTC_ID" CHAR(8) NOT NULL ENABLE, 
	"CNTC_NM" VARCHAR2(100), 
	"PROVD_INSTT_ID" CHAR(8), 
	"PROVD_SYS_ID" CHAR(8), 
	"PROVD_SVC_ID" CHAR(8), 
	"REQUST_INSTT_ID" CHAR(8), 
	"REQUST_SYS_ID" CHAR(8), 
	"CONFM_AT" CHAR(1), 
	"USE_AT" CHAR(1), 
	"VALID_BGNDE" CHAR(20), 
	"VALID_ENDDE" CHAR(20), 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"CNTC_TY" VARCHAR2(60), 
	 CONSTRAINT "COMTNSYSTEMCNTC_PK" PRIMARY KEY ("CNTC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."CNTC_ID" IS '연계ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."CNTC_NM" IS '연계명';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."PROVD_INSTT_ID" IS '제공기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."PROVD_SYS_ID" IS '제공시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."PROVD_SVC_ID" IS '제공서비스ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."REQUST_INSTT_ID" IS '요청기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."REQUST_SYS_ID" IS '요청시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."CONFM_AT" IS '승인여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."VALID_BGNDE" IS '유효시작일자';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."VALID_ENDDE" IS '유효종료일자';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNSYSTEMCNTC"."CNTC_TY" IS '연계유형';
 
   COMMENT ON TABLE "JOEL"."COMTNSYSTEMCNTC"  IS '시스템연계';

CREATE TABLE "JOEL"."COMTNTMPLATINFO" 
   (	"TMPLAT_ID" CHAR(20) NOT NULL ENABLE, 
	"TMPLAT_NM" VARCHAR2(255), 
	"TMPLAT_COURS" VARCHAR2(2000), 
	"USE_AT" CHAR(1), 
	"TMPLAT_SE_CODE" CHAR(6), 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	 CONSTRAINT "COMTNTMPLATINFO_PK" PRIMARY KEY ("TMPLAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."TMPLAT_ID" IS '템플릿ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."TMPLAT_NM" IS '템플릿명';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."TMPLAT_COURS" IS '템플릿경로';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."USE_AT" IS '사용여부';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."TMPLAT_SE_CODE" IS '템플릿구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTMPLATINFO"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON TABLE "JOEL"."COMTNTMPLATINFO"  IS '템플릿';

CREATE TABLE "JOEL"."COMTNTRSMRCVLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"OCCRRNC_DE" CHAR(20), 
	"TRSMRCV_SE_CODE" CHAR(3), 
	"CNTC_ID" CHAR(8), 
	"PROVD_INSTT_ID" CHAR(8), 
	"PROVD_SYS_ID" CHAR(8), 
	"PROVD_SVC_ID" CHAR(8), 
	"REQUST_INSTT_ID" CHAR(8), 
	"REQUST_SYS_ID" CHAR(8), 
	"REQUST_TRNSMIT_TM" VARCHAR2(14), 
	"REQUST_RECPTN_TM" VARCHAR2(14), 
	"RSPNS_TRNSMIT_TM" VARCHAR2(14), 
	"RSPNS_RECPTN_TM" VARCHAR2(14), 
	"RESULT_CODE" VARCHAR2(4), 
	"RESULT_MSSAGE" VARCHAR2(4000), 
	"FRST_REGIST_PNTTM" DATE, 
	"RQESTER_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTNTRSMRCVLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."REQUST_ID" IS '요청ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."TRSMRCV_SE_CODE" IS '송수신구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."CNTC_ID" IS '연계ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."PROVD_INSTT_ID" IS '제공기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."PROVD_SYS_ID" IS '제공시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."PROVD_SVC_ID" IS '제공서비스ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."REQUST_INSTT_ID" IS '요청기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."REQUST_SYS_ID" IS '요청시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."REQUST_TRNSMIT_TM" IS '요청송신시각';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."REQUST_RECPTN_TM" IS '요청수신시각';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."RSPNS_TRNSMIT_TM" IS '응답송신시각';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."RSPNS_RECPTN_TM" IS '응답수신시각';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."RESULT_CODE" IS '결과코드';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."RESULT_MSSAGE" IS '결과메시지';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVLOG"."RQESTER_ID" IS '요청자ID';
 
   COMMENT ON TABLE "JOEL"."COMTNTRSMRCVLOG"  IS '송수신로그';

CREATE TABLE "JOEL"."COMTNTRSMRCVMNTRNG" 
   (	"CNTC_ID" CHAR(8) NOT NULL ENABLE, 
	"TEST_CLASS_NM" VARCHAR2(255), 
	"MNGR_NM" VARCHAR2(60), 
	"MNGR_EMAIL_ADRES" VARCHAR2(50), 
	"MNTRNG_STTUS" CHAR(2), 
	"CREAT_DT" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"FRST_REGIST_PNTTM" DATE NOT NULL ENABLE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE NOT NULL ENABLE, 
	 CONSTRAINT "COMTNTRSMRCVMNTRNG_PK" PRIMARY KEY ("CNTC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."CNTC_ID" IS '연계ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."TEST_CLASS_NM" IS '테스트클래스명';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."MNGR_NM" IS '관리자명';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."MNGR_EMAIL_ADRES" IS '관리자이메일주소';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."MNTRNG_STTUS" IS '모니터링상태';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."CREAT_DT" IS '생성일시';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNTRSMRCVMNTRNG"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON TABLE "JOEL"."COMTNTRSMRCVMNTRNG"  IS '송수신모니터링';

CREATE TABLE "JOEL"."COMTNUSERLOG" 
   (	"OCCRRNC_DE" CHAR(20) NOT NULL ENABLE, 
	"RQESTER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"METHOD_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CREAT_CO" NUMBER(10,0), 
	"UPDT_CO" NUMBER(10,0), 
	"RDCNT" NUMBER(10,0), 
	"DELETE_CO" NUMBER(10,0), 
	"OUTPT_CO" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTNUSERLOG_PK" PRIMARY KEY ("OCCRRNC_DE", "RQESTER_ID", "SVC_NM", "METHOD_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."RQESTER_ID" IS '요청자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."SVC_NM" IS '서비스명';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."METHOD_NM" IS '메서드명';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."CREAT_CO" IS '생성수';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."UPDT_CO" IS '수정수';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."RDCNT" IS '조회수';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."DELETE_CO" IS '삭제수';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."OUTPT_CO" IS '출력수';
 
   COMMENT ON COLUMN "JOEL"."COMTNUSERLOG"."ERROR_CO" IS '오류수';
 
   COMMENT ON TABLE "JOEL"."COMTNUSERLOG"  IS '사용자로그';

CREATE TABLE "JOEL"."COMTNWEBLOG" 
   (	"REQUST_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"OCCRRNC_DE" CHAR(20), 
	"URL" VARCHAR2(100), 
	"RQESTER_ID" VARCHAR2(20), 
	"RQESTER_IP" VARCHAR2(23), 
	 CONSTRAINT "COMTNWEBLOG_PK" PRIMARY KEY ("REQUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTNWEBLOG"."REQUST_ID" IS '요청ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNWEBLOG"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTNWEBLOG"."URL" IS 'URL';
 
   COMMENT ON COLUMN "JOEL"."COMTNWEBLOG"."RQESTER_ID" IS '요청자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTNWEBLOG"."RQESTER_IP" IS '요청자IP';
 
   COMMENT ON TABLE "JOEL"."COMTNWEBLOG"  IS '웹로그';

CREATE TABLE "JOEL"."COMTRDNMADRZIP" 
   (	"RDMN_CODE" VARCHAR2(12) NOT NULL ENABLE, 
	"SN" NUMBER(10,0) NOT NULL ENABLE, 
	"CTPRVN_NM" VARCHAR2(20), 
	"SIGNGU_NM" VARCHAR2(20), 
	"RDMN" VARCHAR2(60), 
	"BDNBR_MNNM" VARCHAR2(5), 
	"BDNBR_SLNO" VARCHAR2(5), 
	"BULD_NM" VARCHAR2(60), 
	"DETAIL_BULD_NM" VARCHAR2(60), 
	"ZIP" VARCHAR2(6) NOT NULL ENABLE, 
	"FRST_REGIST_PNTTM" DATE, 
	"FRST_REGISTER_ID" VARCHAR2(20), 
	"LAST_UPDT_PNTTM" DATE, 
	"LAST_UPDUSR_ID" VARCHAR2(20), 
	 CONSTRAINT "COMTRDNMADRZIP_PK" PRIMARY KEY ("SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."RDMN_CODE" IS '도로명코드';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."SN" IS '일련번호';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."CTPRVN_NM" IS '시도명';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."SIGNGU_NM" IS '시군구명';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."RDMN" IS '도로명';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."BDNBR_MNNM" IS '건물번호본번';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."BDNBR_SLNO" IS '건물번호부번';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."BULD_NM" IS '건물명';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."DETAIL_BULD_NM" IS '상세건물명';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."ZIP" IS '우편번호';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."FRST_REGIST_PNTTM" IS '최초등록시점';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."FRST_REGISTER_ID" IS '최초등록자ID';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."LAST_UPDT_PNTTM" IS '최종수정시점';
 
   COMMENT ON COLUMN "JOEL"."COMTRDNMADRZIP"."LAST_UPDUSR_ID" IS '최종수정자ID';
 
   COMMENT ON TABLE "JOEL"."COMTRDNMADRZIP"  IS '도로명주소';

CREATE TABLE "JOEL"."COMTSSYSLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(20) NOT NULL ENABLE, 
	"SVC_NM" VARCHAR2(255) NOT NULL ENABLE, 
	"METHOD_NM" VARCHAR2(60) NOT NULL ENABLE, 
	"CREAT_CO" NUMBER(10,0), 
	"UPDT_CO" NUMBER(10,0), 
	"RDCNT" NUMBER(10,0), 
	"DELETE_CO" NUMBER(10,0), 
	"OUTPT_CO" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTSSYSLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "SVC_NM", "METHOD_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."SVC_NM" IS '서비스명';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."METHOD_NM" IS '메서드명';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."CREAT_CO" IS '생성수';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."UPDT_CO" IS '수정수';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."RDCNT" IS '조회수';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."DELETE_CO" IS '삭제수';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."OUTPT_CO" IS '출력수';
 
   COMMENT ON COLUMN "JOEL"."COMTSSYSLOGSUMMARY"."ERROR_CO" IS '오류수';
 
   COMMENT ON TABLE "JOEL"."COMTSSYSLOGSUMMARY"  IS '시스템로그요약';

CREATE TABLE "JOEL"."COMTSTRSMRCVLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(20) NOT NULL ENABLE, 
	"TRSMRCV_SE_CODE" CHAR(3) NOT NULL ENABLE, 
	"PROVD_INSTT_ID" CHAR(8) NOT NULL ENABLE, 
	"PROVD_SYS_ID" CHAR(8) NOT NULL ENABLE, 
	"PROVD_SVC_ID" CHAR(8) NOT NULL ENABLE, 
	"REQUST_INSTT_ID" CHAR(8) NOT NULL ENABLE, 
	"REQUST_SYS_ID" CHAR(8) NOT NULL ENABLE, 
	"RDCNT" NUMBER(10,0), 
	"ERROR_CO" NUMBER(10,0), 
	 CONSTRAINT "COMTSTRSMRCVLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "TRSMRCV_SE_CODE", "PROVD_INSTT_ID", "PROVD_SYS_ID", "PROVD_SVC_ID", "REQUST_INSTT_ID", "REQUST_SYS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."TRSMRCV_SE_CODE" IS '송수신구분코드';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."PROVD_INSTT_ID" IS '제공기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."PROVD_SYS_ID" IS '제공시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."PROVD_SVC_ID" IS '제공서비스ID';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."REQUST_INSTT_ID" IS '요청기관ID';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."REQUST_SYS_ID" IS '요청시스템ID';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."RDCNT" IS '조회수';
 
   COMMENT ON COLUMN "JOEL"."COMTSTRSMRCVLOGSUMMARY"."ERROR_CO" IS '오류수';
 
   COMMENT ON TABLE "JOEL"."COMTSTRSMRCVLOGSUMMARY"  IS '송수신로그요약';

CREATE TABLE "JOEL"."COMTSWEBLOGSUMMARY" 
   (	"OCCRRNC_DE" CHAR(20) NOT NULL ENABLE, 
	"URL" VARCHAR2(100) NOT NULL ENABLE, 
	"RDCNT" NUMBER(10,0), 
	 CONSTRAINT "COMTSWEBLOGSUMMARY_PK" PRIMARY KEY ("OCCRRNC_DE", "URL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "TS_PRACTICE" ;
 

   COMMENT ON COLUMN "JOEL"."COMTSWEBLOGSUMMARY"."OCCRRNC_DE" IS '발생일';
 
   COMMENT ON COLUMN "JOEL"."COMTSWEBLOGSUMMARY"."URL" IS 'URL';
 
   COMMENT ON COLUMN "JOEL"."COMTSWEBLOGSUMMARY"."RDCNT" IS '조회수';
 
   COMMENT ON TABLE "JOEL"."COMTSWEBLOGSUMMARY"  IS '웹로그 요약';
